services:
  postgres:
    container_name: postgres-18
    image: postgres:18-alpine
    volumes:
      - ./data:/var/lib/postgresql/18/docker
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
